// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAcfi_jk9uVI9DtBtfLx89O1Xiq3j12A',
    appId: '1:887142970943:android:c2bc8c700d199bc2a3ea8a',
    messagingSenderId: '887142970943',
    projectId: 'valeapp-flutter',
    authDomain: 'valeapp-flutter.firebaseapp.com',
    storageBucket: 'valeapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-m-lZLBVe8ze2G4Q5GuCvJsq_k7N02kg',
    appId: '1:887142970943:android:c2bc8c700d199bc2a3ea8a',
    messagingSenderId: '887142970943',
    projectId: 'valeapp-flutter',
    storageBucket: 'valeapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbnh7fVGkQIm1U7dnpNcaopcyhzOLSoVQ',
    appId: '1:887142970943:android:c2bc8c700d199bc2a3ea8a',
    messagingSenderId: '887142970943',
    projectId: 'valeapp-flutter',
    storageBucket: 'valeapp-flutter.firebasestorage.app',
    iosClientId: '887142970943-rtitjigqmidpbe52ttd53qn23l5l22m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTuvale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbnh7fVGkQIm1U7dnpNcaopcyhzOLSoVQ',
    appId: '1:887142970943:android:c2bc8c700d199bc2a3ea8a',
    messagingSenderId: '887142970943',
    projectId: 'valeapp-flutter',
    storageBucket: 'valeapp-flutter.firebasestorage.app',
    iosClientId: '887142970943-rtitjigqmidpbe52ttd53qn23l5l22m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTuvale',
  );
}
